---
- name: Monitor vserver
  hosts: remote_server
  become: yes
  tasks:

  - name: Verificar proceso
    remote_user: root
    shell: pgrep -x vServer
    register: pgrep_result
    ignore_errors: yes

  - name: Imprimir resultado
    debug:
      msg: "El proceso vServer está  {{ 'en ejecución' if pgrep_result.rc == 0 else 'detenido' }}"

  - name: Reiniciar
    shell: /home/user/velneo/Velneo-vServer/vServer.sh -t && /home/user/velneo/Velneo-vServer/vServer>
    when: pgrep_result.rc != 0


