---
- name: Monitor vserver
  hosts: remote_server
  become: yes
  tasks:

  - name: Verificar proceso
    remote_user: root
    shell: pgrep -x vServer
    register: pgrep_result
    ignore_errors: yes

#  - name: Imprimir resultado
#    debug:
#      msg: "El proceso vServer est치  {{ 'en ejecuci칩n' if pgrep_result.rc == 0 else 'detenido' }}"

  - name: Almacenar resultado en archivo
    local_action: copy content="{{ 'El proceso vServer est치  en ejecuci칩n' if pgrep_result.rc == 0 else 'El proceso >

  - name: Reiniciar
    shell: /home/user/velneo/Velneo-vServer/vServer.sh -t && /home/user/velneo/Velneo-vServer/vServer.sh -s
    when: pgrep_result.rc != 0
